- import_role:
    name: kubectl
  vars:
    name: @= project_name =@
    kubectl_content: |
      {{lookup('template', 'configmap.yml') }}
      ---
      {{lookup('template', 'deployment.yml') }}
      ---
      {{lookup('template', 'ingress.yml') }}
      ---
      {{lookup('template', 'secret.yml') }}
      ---
      {{lookup('template', 'service.yml') }}
      ---
      {{lookup('template', 'servicemonitor.yml') }}
  tags: @= project_name =@